server:
  port: 8010

logging:
  config: classpath:logback-spring.xml
  level:
    com.sakura.order.feign: debug # 这里我们可以单独配置feign的日志级别
    com.sakura.order.mapper: debug # 使用logging方式打印SQL日志，方便查看logid

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.43.128:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: px123456
    # 使用druid数据源
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.43.128:9100
  redis:
    host: 192.168.43.118
    port: 6379
    password: px123456

seata:
  tx-service-group: order-tx-group
  service:
    vgroupMapping:
      order-tx-group: default
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: f6758f0e-1bbe-484f-9247-e9e6d1df5a25
      group: SEATA_GROUP
      username: ${spring.cloud.nacos.config.username}
      password: ${spring.cloud.nacos.config.password}
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: f6758f0e-1bbe-484f-9247-e9e6d1df5a25
      group: SEATA_GROUP
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 关闭这个日志打印，使用上面的logging日志打印方式
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" #逻辑未删除值(默认为 N)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sakura.order.entity

feign:
  sentinel:
    enabled: true # 开启openfeign中的sentinel
  client:
    config:
      default:
        request-interceptors:
          - com.sakura.common.interceptor.feign.LogIdFeignInterceptor # 开启全局自定义logID拦截器
      product-service:
        logger-level: basic
        connect-timeout: 5000 # 连接超时时间，默认2s
        read-timeout: 6000 #请求处理超时时间，默认5s
        request-interceptors:
          - com.sakura.order.interceptor.feign.CustomFeignInterceptor # 开启自定义拦截器
