server:
  port: 8000

logging:
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.43.128:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: px123456
    # 使用druid数据源
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.43.128:9100
    gateway:
      # 全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      # 路由规则配置
      routes:
        - id: base-service
          uri: lb://base-service
          predicates:
            - Path=/api-base/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api-user/**
          filters:
            - StripPrefix=1
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api-product/**
          filters:
            - StripPrefix=1
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/api-stock/**
          filters:
            - StripPrefix=1
        - id: order-service # 规则ID
          uri: lb://order-service # lb表示启用loadbalancer负载均衡器
          predicates:
            - Path=/api-order/** # 页面请求gateway的ip+端口/api-order就会进入这个断言规则里面，然后转发到上面的order-service服务
          filters:
            - StripPrefix=1 # 这里是去掉上面路径中的/api-order这一层，完整的转发路径是127.0.0.1:8000/api-order/add/order



